import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { oxygen } from "./ui/fonts";
import TopNav from "./ui/nav";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Farine: make better bread",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oxygen.className} antialiased`}>
        <Providers>
          <Container>
            <TopNav />
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
