name: Code Quality

on:
  push: # Runs on all pushes to any branch
    branches:
      - "**" # Matches all branches

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install Dependencies
        run: npm clean-install

      - name: Run ESLint
        run: npm run lint
