name: CI Pipeline for PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write # for checkout and releases
  issues: write # for commenting on released issues
  pull-requests: write # for commenting on pull requests

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install Dependencies
        run: npm clean-install

      - name: Verify Signatures for Dependencies
        run: npm audit signatures

      - name: Run npm Audit
        run: npm audit

      - name: Commit Lint
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel Preview
        id: deploy_preview
        run: |
          BASE_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --yes)
          echo "Preview deployment URL: $BASE_URL"
          echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E Tests
        env:
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: |
          npm run test:e2e
