name: CI Pipeline for PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write # for checkout and releases
  issues: write # for commenting on released issues
  pull-requests: write # for commenting on pull requests

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install

      - name: Verify Signatures for Dependencies
        run: npm audit signatures

      - name: Run npm Audit
        run: npm audit

      - name: Commit Lint
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run Unit Tests
        run: npm run test:unit

  deploy-preview:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel Preview
        id: deploy_preview
        run: |
          PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --confirm)
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

  e2e-tests:
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright E2E Tests
        env:
          BASE_URL: ${{ env.PREVIEW_URL }}
        run: npm run test:e2e

  promote:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Promote Preview to Production
        if: ${{ success() }}
        run: vercel deploy promote --token=${{ secrets.VERCEL_TOKEN }}

      # Run semantic release only if the production deployment was successful
      - name: Run Semantic Release and Publish Release Notes
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install semantic-release @semantic-release/changelog @semantic-release/git
          npx semantic-release
